DROP TABLE IF EXISTS [DriverArts];
CREATE TABLE [DriverArts] (
  [ID] INTEGER  NOT NULL UNIQUE
, [WeaponTypeID] INTEGER  NOT NULL
, [DriverID] INTEGER  NOT NULL
, [Name_EN] text NOT NULL
, [Name_CN] text NOT NULL
, CONSTRAINT [PK_DriverArts] PRIMARY KEY ([ID])
, FOREIGN KEY ([DriverID]) REFERENCES [Drivers] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
, FOREIGN KEY ([WeaponTypeID]) REFERENCES [WeaponTypes] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);
