DROP TABLE IF EXISTS [PoppiPowerLevels];
CREATE TABLE [PoppiPowerLevels] (
  [ID] INTEGER  NOT NULL UNIQUE
, [1005] INTEGER NOT NULL
, [1006] INTEGER NOT NULL
, [1007] INTEGER NOT NULL
, CONSTRAINT [sqlite_master_PK_PoppiPowerLevels] PRIMARY KEY ([ID])
);
