DROP TABLE IF EXISTS [Weapons];
CREATE TABLE [Weapons] (
  [ID] INTEGER  NOT NULL UNIQUE
, [WeaponTypeID] INTEGER  NOT NULL
, [CoreChipID] INTEGER  NOT NULL
, [Name_EN] text NOT NULL
, [Name_CN] text NOT NULL
, CONSTRAINT [PK_WeaponNames] PRIMARY KEY ([ID])
, FOREIGN KEY ([WeaponTypeID]) REFERENCES [Weapons] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
, FOREIGN KEY ([CoreChipID]) REFERENCES [Items] ([ID]) ON DELETE NO ACTION ON UPDATE NO ACTION
);
